<section aria-labelledby="billing-orders-support-heading">
    <h2 id="billing-orders-support-heading">{{ __('Order support') }}</h2>
    @if (session('billing-orders-support-message'))<p role="status">{{ session('billing-orders-support-message') }}</p>@endif
    <form wire:submit="createQuote"><h3>{{ __('Create quote') }}</h3><label>{{ __('Currency') }} <input wire:model="currency" maxlength="3" required></label><label>{{ __('Total') }} <input wire:model="quoteTotalMinor" type="number" min="0" required></label><label>{{ __('Items (JSON array)') }} <textarea wire:model="quoteItems" required></textarea></label><button type="submit">{{ __('Create quote') }}</button></form>
    <ul wire:loading.class="opacity-50">@forelse ($quotes as $quote)<li wire:key="quote-{{ $quote->id }}">{{ $quote->quote_number }} ({{ $quote->status }})</li>@empty<li>{{ __('No quotes found.') }}</li>@endforelse</ul>
    <form wire:submit="createCart"><h3>{{ __('Create cart') }}</h3><label>{{ __('Items (JSON array)') }} <textarea wire:model="cartItems" required></textarea></label><button type="submit">{{ __('Create cart') }}</button></form>
    <ul>@forelse ($carts as $cart)<li wire:key="cart-{{ $cart->id }}">Cart {{ $cart->id }} ({{ $cart->status }}) <button type="button" wire:click="$set('selectedCartId', {{ $cart->id }})">{{ __('Select') }}</button></li>@empty<li>{{ __('No carts found.') }}</li>@endforelse</ul>
    @if ($selectedCartId)<form wire:submit="checkoutCart"><label>{{ __('Subtotal') }} <input wire:model="cartSubtotalMinor" type="number" min="0" required></label><button type="submit">{{ __('Checkout cart') }}</button></form>@endif
    <ul>@forelse ($orders as $order)<li wire:key="support-order-{{ $order->id }}">{{ $order->order_number }} ({{ $order->status->value }}) <button type="button" wire:click="$set('selectedOrderId', {{ $order->id }})">{{ __('Select') }}</button></li>@empty<li>{{ __('No orders found.') }}</li>@endforelse</ul>
    @if ($selectedOrderId)<form wire:submit="transitionOrder"><select wire:model="orderStatus"><option value="draft">{{ __('Draft') }}</option><option value="pending_review">{{ __('Pending review') }}</option><option value="approved">{{ __('Approved') }}</option><option value="rejected">{{ __('Rejected') }}</option><option value="cancelled">{{ __('Cancelled') }}</option><option value="completed">{{ __('Completed') }}</option></select><button type="submit">{{ __('Update order') }}</button></form>@endif
</section>
